In [1]:
a = 5
a

5

In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------------- ------------------- 6.6/12.6 MB 40.3 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 26.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 20.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 18.0 MB/s eta 0:00:00


In [3]:
import numpy as np

## numpy.zeros()
Belirtilen boyutlarda sıfırlardan oluşan bir dizi oluşturur

In [4]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## 2- numpy.ones()
Belirtilen boyutlarda birlerden oluşan bir dizi oluşturur

In [5]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

## 3-numpy.linespace()
belirtilen başlangıç ve bitiş noktaları arasında eşit aralıklı sayılar oluşturur

In [7]:
arr3 = np.linspace(0, 10, 5)
arr3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 4- numpy.mean()
bir dizinin ortalamasını almamızı sağlar

In [10]:
arr4 = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr4)
print(mean)

3.0


## 5- numpy.sum()
bir dizideki tüm elemanların toplamını hesaplamaya yardımcı olur

In [12]:
arr5 = np.array([1, 2, 3, 4, 5])
summ = np.sum(arr5)
print(summ)

15


## 6- numpy.reshape()
bir dizinin şeklini değiştirmeye yardım eder

In [15]:
arr6 = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (2, 3))
reshaped

array([[0., 0., 0.],
       [0., 0., 0.]])

## 7- numpy.max()
bir dizideki en büyük değeri bulmaya yardımcı olur

In [17]:
arr7 = np.array([1, 2, 3, 4, 5])
maxx = np.max(arr7)
print(maxx)

5


## 8- numpy.dot()
iki dizinin dot productunu bulmamıza olanak sağlar

In [19]:
arr81 = np.array([1, 2])
arr82 = np.array([3, 4])
dot_product = np.dot(arr81, arr82)
print(dot_product)

11


## 9-numpy.sort()
bir diziyi sıralamaya olanak sağlar

In [21]:
arr9 = np.array([12, 92, 323, 14, 5])
sortedd = np.sort(arr9)
print(sortedd)

[  5  12  14  92 323]


## 10- numpy.all()
bir dizinin tüm elemanlarının belirli bir koşulu sağladığını kontrol eder

In [25]:
arr10 = np.array([True, True, False])
result = np.all(arr)
print(result)


False
